import type { EditorLevel } from './types';

/**
 * Generate a valid TypeScript source file from the editor level data
 * that can be dropped into src/data/ and used by the game engine.
 */
export function exportLevelToTS(level: EditorLevel): string {
  const lines: string[] = [];
  const zoneKeys = Object.keys(level.zones);

  lines.push(`import { TILE } from '../config/constants';`);
  lines.push(`import type { LevelDefinition } from './levels';`);
  lines.push('');
  lines.push(`/**`);
  lines.push(` * ${level.displayName} — Generated by Level Editor`);
  lines.push(` *`);
  lines.push(` * Tile legend:`);
  lines.push(` *   0 = empty`);
  lines.push(` *   1 = ground`);
  lines.push(` *   2 = brick (breakable)`);
  lines.push(` *   3 = item block (coin)`);
  lines.push(` *   4 = item block (powerup / mushroom)`);
  lines.push(` *   5 = solid block (non-breakable)`);
  lines.push(` *   6 = fire flower item block`);
  lines.push(` *   7 = pipe body`);
  lines.push(` *   8 = pipe top`);
  lines.push(` *   9 = jump pad`);
  lines.push(` */`);
  lines.push('');

  // Emit each zone's map, enemies, coins
  for (const zoneKey of zoneKeys) {
    const zone = level.zones[zoneKey];
    const varPrefix = zoneKey === 'overworld' ? '' : `${zoneKey.toUpperCase()}_`;

    // Map
    lines.push(`// prettier-ignore`);
    lines.push(`const ${varPrefix}MAP: number[][] = [`);

    // Column header comment
    const colNums = Array.from({ length: zone.cols }, (_, i) => String(i).padStart(2, ' ')).join(' ');
    lines.push(`// ${colNums}`);

    for (let r = 0; r < zone.rows; r++) {
      const row = zone.map[r].map((v) => String(v)).join(', ');
      lines.push(`  [${row}],`);
    }
    lines.push(`];`);
    lines.push('');

    // Enemies — y is computed so the enemy's feet sit at the bottom of the placed cell
    lines.push(`const ${varPrefix}ENEMIES = [`);
    for (const enemy of zone.enemies) {
      const yOffset = enemy.type === 'turtle' ? 52 : enemy.type === 'flyer' ? 0 : 44;
      if (enemy.type === 'flyer') {
        lines.push(`  { type: '${enemy.type}' as const, x: ${enemy.col} * TILE, y: ${enemy.row} * TILE },`);
      } else {
        lines.push(`  { type: '${enemy.type}' as const, x: ${enemy.col} * TILE, y: ${enemy.row + 1} * TILE - ${yOffset} },`);
      }
    }
    lines.push(`];`);
    lines.push('');

    // Coins
    lines.push(`const ${varPrefix}COINS = [`);
    for (const coin of zone.coins) {
      lines.push(`  { x: ${coin.col} * TILE + 4, y: ${coin.row} * TILE },`);
    }
    lines.push(`];`);
    lines.push('');
  }

  // Flag and player start
  lines.push(`const FLAG_POS = { x: ${level.flagCol} * TILE - 10, y: ${level.flagRow} * TILE };`);
  lines.push(`const PLAYER_START = { x: ${level.playerStartCol} * TILE, y: ${level.playerStartRow} * TILE - 48 };`);
  lines.push('');

  // Warp pipes
  if (level.warpPipes.length > 0) {
    lines.push(`const WARP_PIPES = [`);
    for (const wp of level.warpPipes) {
      lines.push(`  {`);
      lines.push(`    id: '${wp.id}',`);
      lines.push(`    entryZone: '${wp.entryZone}',`);
      lines.push(`    entryCol: ${wp.entryCol},`);
      lines.push(`    entryRow: ${wp.entryRow},`);
      lines.push(`    exitZone: '${wp.exitZone}',`);
      lines.push(`    exitCol: ${wp.exitCol},`);
      lines.push(`    exitRow: ${wp.exitRow},`);
      lines.push(`    exitPlayerX: ${wp.exitPlayerCol} * TILE,`);
      lines.push(`    exitPlayerY: ${wp.exitPlayerRow} * TILE,`);
      lines.push(`    emergeDirection: '${wp.emergeDirection}' as const,`);
      lines.push(`  },`);
    }
    lines.push(`];`);
  } else {
    lines.push(`const WARP_PIPES: never[] = [];`);
  }
  lines.push('');

  // Final export
  const exportName = `LEVEL_${level.id.replace(/[^a-zA-Z0-9]/g, '_').toUpperCase()}`;
  lines.push(`export const ${exportName}: LevelDefinition = {`);
  lines.push(`  id: '${level.id}',`);
  lines.push(`  displayName: '${level.displayName}',`);
  lines.push(`  playerStart: PLAYER_START,`);
  lines.push(`  flagPos: FLAG_POS,`);
  lines.push(`  zones: {`);

  for (const zoneKey of zoneKeys) {
    const zone = level.zones[zoneKey];
    const varPrefix = zoneKey === 'overworld' ? '' : `${zoneKey.toUpperCase()}_`;
    lines.push(`    ${zoneKey}: {`);
    lines.push(`      id: '${zoneKey}',`);
    lines.push(`      kind: '${zone.kind}',`);
    lines.push(`      map: ${varPrefix}MAP,`);
    lines.push(`      enemies: ${varPrefix}ENEMIES,`);
    lines.push(`      coins: ${varPrefix}COINS,`);
    lines.push(`    },`);
  }

  lines.push(`  },`);
  lines.push(`  warpPipes: WARP_PIPES,`);
  lines.push(`};`);
  lines.push('');

  return lines.join('\n');
}

/** Trigger a file download in the browser */
export function downloadFile(content: string, filename: string): void {
  const blob = new Blob([content], { type: 'text/typescript' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
